= Calculate stock price ratios
:toc:
:sectnums:
:sectnumlevels: 4

Python helper library.
It consists of functions which can be used in multiple projects.

== Usage
. use this repository as _git_ submodule: `git submodule add git@github.com:bzgec/python_helperLib.git helperLib`
. import it to your _python_ project as module: `from helperLib.helper import sprintf, printf`
. you can also use link:mailSender.py[] from terminal

== Development
Before each commit check source code with `make check` command.

WARNING: If there are some errors fix them before committing!

Or you can just run `make commit` which will run all the necessary commands before running
`git commit`.
Note that you still need to add files to index (`git add`).

=== Dependencies
* https://www.gnu.org/software/make/[GNU - make]
* `pip` link:requirements.dev.txt[requirements.dev.txt]
* `shellcheck` - a static analysis tool for shell scripts

== License
See the link:./LICENSE.adoc[LICENSE] file for license rights and limitations (MIT).

== TODO
